# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Jan 11 23:10:20 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from icons import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

def getImage(icon_name):
    image = QtGui.QImage()
    bytearr = QtCore.QByteArray.fromBase64( icon_name )
    image.loadFromData(bytearr, 'PNG')
    return QtGui.QPixmap.fromImage(image)

class Ui_DataExplorer(object):
    def setupUi(self, DataExplorer):
        DataExplorer.setObjectName(_fromUtf8("DataExplorer"))
        DataExplorer.resize(573, 407)
        self.centralwidget = QtGui.QWidget(DataExplorer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        DataExplorer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DataExplorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuApp = QtGui.QMenu(self.menubar)
        self.menuApp.setObjectName(_fromUtf8("menuApp"))
        DataExplorer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DataExplorer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DataExplorer.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DataExplorer)
        self.toolBar.setMovable(True)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DataExplorer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCreate = QtGui.QAction(DataExplorer)
        self.actionCreate.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(getImage(ADD), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate.setIcon(icon)
        self.actionCreate.setObjectName(_fromUtf8("actionCreate"))
        self.actionEdit = QtGui.QAction(DataExplorer)
        self.actionEdit.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(getImage(PENCIL), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon1)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionDelete = QtGui.QAction(DataExplorer)
        self.actionDelete.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(getImage(CROSS), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon2)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionAbout = QtGui.QAction(DataExplorer)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionConnection = QtGui.QAction(DataExplorer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(getImage(CON), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnection.setIcon(icon3)
        self.actionConnection.setObjectName(_fromUtf8("actionConnection"))
        self.actionQuit = QtGui.QAction(DataExplorer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(getImage(DISCON), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuAction.addAction(self.actionCreate)
        self.menuAction.addAction(self.actionEdit)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionDelete)
        self.menuHelp.addAction(self.actionAbout)
        self.menuApp.addAction(self.actionConnection)
        self.menuApp.addSeparator()
        self.menuApp.addAction(self.actionQuit)
        self.menubar.addAction(self.menuApp.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionCreate)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionDelete)

        self.retranslateUi(DataExplorer)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), DataExplorer.close)
        QtCore.QMetaObject.connectSlotsByName(DataExplorer)

    def retranslateUi(self, DataExplorer):
        DataExplorer.setWindowTitle(_translate("DataExplorer", "Postgresql Data Explorer", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DataExplorer", "ID", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DataExplorer", "NAMA", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DataExplorer", "TGL LAHIR", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DataExplorer", "KELAMIN", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DataExplorer", "ALAMAT", None))
        self.menuAction.setTitle(_translate("DataExplorer", "Action", None))
        self.menuHelp.setTitle(_translate("DataExplorer", "Help", None))
        self.menuApp.setTitle(_translate("DataExplorer", "App", None))
        self.toolBar.setWindowTitle(_translate("DataExplorer", "toolBar", None))
        self.actionCreate.setText(_translate("DataExplorer", "Create", None))
        self.actionCreate.setStatusTip(_translate("DataExplorer", "Memasukan Record", None))
        self.actionCreate.setShortcut(_translate("DataExplorer", "Ctrl+N", None))
        self.actionEdit.setText(_translate("DataExplorer", "Edit", None))
        self.actionEdit.setStatusTip(_translate("DataExplorer", "Mengubah Record", None))
        self.actionEdit.setShortcut(_translate("DataExplorer", "Ctrl+E", None))
        self.actionDelete.setText(_translate("DataExplorer", "Delete", None))
        self.actionDelete.setStatusTip(_translate("DataExplorer", "Menghapus Record", None))
        self.actionDelete.setShortcut(_translate("DataExplorer", "Ctrl+D", None))
        self.actionAbout.setText(_translate("DataExplorer", "About", None))
        self.actionConnection.setText(_translate("DataExplorer", "Connection", None))
        self.actionConnection.setShortcut(_translate("DataExplorer", "Ctrl+Shift+C", None))
        self.actionQuit.setText(_translate("DataExplorer", "Quit", None))
        self.actionQuit.setShortcut(_translate("DataExplorer", "Ctrl+Q", None))



class Ui_ConnForm(object):
    def setupUi(self, ConnForm):
        ConnForm.setObjectName(_fromUtf8("ConnForm"))
        ConnForm.resize(325, 191)
        self.gridLayout_2 = QtGui.QGridLayout(ConnForm)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(ConnForm)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.userInput = QtGui.QLineEdit(ConnForm)
        self.userInput.setObjectName(_fromUtf8("userInput"))
        self.gridLayout.addWidget(self.userInput, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(ConnForm)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.passwdInput = QtGui.QLineEdit(ConnForm)
        self.passwdInput.setEchoMode(QtGui.QLineEdit.Password)
        self.passwdInput.setObjectName(_fromUtf8("passwdInput"))
        self.gridLayout.addWidget(self.passwdInput, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(ConnForm)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.hostInput = QtGui.QLineEdit(ConnForm)
        self.hostInput.setObjectName(_fromUtf8("hostInput"))
        self.gridLayout.addWidget(self.hostInput, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(ConnForm)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dbInput = QtGui.QLineEdit(ConnForm)
        self.dbInput.setObjectName(_fromUtf8("dbInput"))
        self.gridLayout.addWidget(self.dbInput, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeBtn = QtGui.QPushButton(ConnForm)
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout.addWidget(self.closeBtn)
        self.connBtn = QtGui.QPushButton(ConnForm)
        self.connBtn.setObjectName(_fromUtf8("connBtn"))
        self.horizontalLayout.addWidget(self.connBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(ConnForm)
        QtCore.QObject.connect(self.closeBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), ConnForm.close)
        QtCore.QMetaObject.connectSlotsByName(ConnForm)

    def retranslateUi(self, ConnForm):
        ConnForm.setWindowTitle(_translate("ConnForm", "Connect to Postgres", None))
        self.label.setText(_translate("ConnForm", "User", None))
        self.label_2.setText(_translate("ConnForm", "Password", None))
        self.label_3.setText(_translate("ConnForm", "Host", None))
        self.label_4.setText(_translate("ConnForm", "Database", None))
        self.closeBtn.setText(_translate("ConnForm", "Close", None))
        self.connBtn.setText(_translate("ConnForm", "Connect", None))


class Ui_InsertDialog(object):
    def setupUi(self, InsertDialog):
        InsertDialog.setObjectName(_fromUtf8("InsertDialog"))
        InsertDialog.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(InsertDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(InsertDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeBtn = QtGui.QPushButton(InsertDialog)
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout.addWidget(self.closeBtn)
        self.insertBtn = QtGui.QPushButton(InsertDialog)
        self.insertBtn.setObjectName(_fromUtf8("insertBtn"))
        self.horizontalLayout.addWidget(self.insertBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.kelaminInput = QtGui.QComboBox(InsertDialog)
        self.kelaminInput.setObjectName(_fromUtf8("kelaminInput"))
        self.kelaminInput.addItem(_fromUtf8(""))
        self.kelaminInput.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.kelaminInput, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(InsertDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.alamatInput = QtGui.QTextEdit(InsertDialog)
        self.alamatInput.setObjectName(_fromUtf8("alamatInput"))
        self.gridLayout.addWidget(self.alamatInput, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(InsertDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(InsertDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.namaInput = QtGui.QLineEdit(InsertDialog)
        self.namaInput.setObjectName(_fromUtf8("namaInput"))
        self.gridLayout.addWidget(self.namaInput, 0, 1, 1, 1)
        self.tglLhrInput = QtGui.QDateEdit(InsertDialog)
        self.tglLhrInput.setObjectName(_fromUtf8("tglLhrInput"))
        self.gridLayout.addWidget(self.tglLhrInput, 1, 1, 1, 1)

        self.retranslateUi(InsertDialog)
        QtCore.QObject.connect(self.closeBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), InsertDialog.close)
        QtCore.QMetaObject.connectSlotsByName(InsertDialog)

    def retranslateUi(self, InsertDialog):
        InsertDialog.setWindowTitle(_translate("InsertDialog", "Input Dialog", None))
        self.label.setText(_translate("InsertDialog", "Nama", None))
        self.closeBtn.setText(_translate("InsertDialog", "Close", None))
        self.insertBtn.setText(_translate("InsertDialog", "Insert", None))
        self.kelaminInput.setItemText(0, _translate("InsertDialog", "Female", None))
        self.kelaminInput.setItemText(1, _translate("InsertDialog", "Male", None))
        self.label_3.setText(_translate("InsertDialog", "Kelamin", None))
        self.label_4.setText(_translate("InsertDialog", "Alamat", None))
        self.label_2.setText(_translate("InsertDialog", "Tgl Lahir", None))
        self.tglLhrInput.setDisplayFormat(_translate("InsertDialog", "yyyy-MM-dd", None))
